### ISSUE TITLE
Xing: Do not import Token on client files

### ISSUE THREAD

**Issue by pgoggles** [Impreffively/Project-Catwalk#49]
https://github.com/Impreffively/Project-Catwalk/blob/b8c6f179dc0208ca604bb7184e02ff7a7d55b4c8/client/src/components/Reviews/ReviewList/ReviewTile.jsx#L7

This is a big security concern, you never want your client or any of your client code to have access to your git token, this in essence bakes the token into your bundle.js, then anyone who visits your page can see your token, and then also control your github. You want to reserve your token to only be on your server side where it is abstracted from visitors to the page.

**Comment by xingvoong** [comment]
right, forgot to remove it.  Thank you! Resolved
